### ISSUE TITLE
Force better use of the .wdn-icon-* classes

### ISSUE THREAD

**Issue by mfairchild365** [unl/wdntemplates#1006]
Right now these classes can be applied to any element, even `h2`, `p`, `video`, etc. We should look at enforcing accessibility best practices when defining these classes.

For example, I can't see any reason why we should limit use of the  `.wdn-icon-*` class to `span`s with `aria-hidden="true"`. In this example, the css rule would change to something like:

```
[class*="wdn-icon-"][aria-hidden="true"]:before
```

It would be great if we could also enforce the presence of an accessible alternative, such as a `<span class="wdn-text-hidden">text alternative</span>` after it, but I'm not sure about the best way to make that work.

One possibility is something like (with the issue that perhaps you walt your alternative text to be visible)

```
<span class="wdn-font-icon-container">
  <span class="wdn-text-hidden">text alternative</span>
  <span class="wdn-icon-rocket"></span>
</span>

<style>
  .wdn-font-icon-container .wdn-text-hidden + .wdn-icon-rocket {
    /*icon jazz*/
  }
</style>
```

**Comment by skoolbus39** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Improvement alignment of icons relative to adjacent text](https://trello.com/c/wYBTGW6y/59-improvement-alignment-of-icons-relative-to-adjacent-text)

**Comment by skoolbus39** [comment]
We should be using SVG icons instead of the 4.1 icon font.
