### ISSUE TITLE
tapping outside of widgets (social) does not close them

### ISSUE THREAD

**Issue by mfairchild365** [unl/wdntemplates#1009]
**Browser:** IOS Safari only

**To reproduce:**
1. open a framework page
2. tap social so that it open its box
3. tab outside of box
4. nothing happens

**Expected result**
tapping outside of box closes the menu, just like clicking outside the box on desktop.

**Comment by kabel** [comment]
See http://stackoverflow.com/questions/3705937/document-click-not-working-correctly-on-iphone-jquery
