### ISSUE TITLE
'N' missing on first print attempt

### ISSUE THREAD

**Issue by ericras** [unl/wdntemplates#1015]
Right now, its a background image that doesn't print. This appears to be where it was removed:

https://github.com/unl/wdntemplates/commit/534d5fbb708e6b677afdbd6508eb8bc51ab6a20f#diff-4b6f632b0d8a9f7362178e6cedf8caf6L110

**Comment by ericras** [comment]
Another option is to use -webkit-print-color-adjust: exact

http://stackoverflow.com/a/21160150

**Comment by ericras** [comment]
http://stackoverflow.com/questions/24680588/load-external-images-in-print-media

**Comment by skoolbus39** [comment]
Logos in 5.0 are SVGs instead of background-images.
