### ISSUE TITLE
anchor offset not working in chrome

### ISSUE THREAD

**Issue by mfairchild365** [unl/wdntemplates#1036]
```
<h2><a class="wdn-offset-anchor" id="target"></a>My heading for jumping to</h2>
<script>
WDN.initializePlugin('anchors');
</script>
```

This does not appear to be working in chrome, but does work in other browsers. At first glance, I'm unable to find a solution.

**Comment by skoolbus39** [comment]
The anchor offset plugin was removed in framework version 5.0. Version 4.1 is no longer supported.
