### ISSUE TITLE
Unexpected footer font-size issues from rem change

### ISSUE THREAD

**Issue by kabel** [unl/wdntemplates#1047]
With the change of the use of the rem function, the footer is not sized properly without developer intervention (changes to the sharedcode). Footers that aren't using the `wdn-footer-module` class are too big.

<img width="1186" alt="screen shot 2017-01-24 at 3 58 46 pm" src="https://cloud.githubusercontent.com/assets/675956/22268726/3065907a-e24e-11e6-89a7-59bc84700ebd.png">

**Comment by skoolbus39** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Unexpected footer font-size issues from rem change](https://trello.com/c/P53qN9t2/27-unexpected-footer-font-size-issues-from-rem-change)
