### ISSUE TITLE
Mediahub location of description and transcript

### ISSUE THREAD

**Issue by snrwebmaster** [unl/wdntemplates#1060]
Is it possible to move the description above the transcript on individual item page?    Or make the transcript an accordion that is closed on default so that people know there is a description.    The description gets lost below the transcript.

**Comment by mfairchild365** [comment]
@snrwebmaster we have been discussing some changes address that issue internally. I've created an issue in the MediaHub repository, so I will close this one. https://github.com/unl/UNL_MediaHub/issues/333
