### ISSUE TITLE
The “itemprop” attribute was specified, but the element is not a property of any item.

### ISSUE THREAD

**Issue by bberberov** [unl/wdntemplates#1082]
Web Audit reports the following error:
https://webaudit.unl.edu/sites/1863/pages/3865768/marks/63894115/

I believe this is the problem, described here:
https://www.drupal.org/node/2389929

I'm not sure this is the right place to report.  if it isn't, please redirect me.  Thanks.

**Comment by mfairchild365** [comment]
Thank you for reporting this @bberberov 

I recreated this issue in our Drupal repository: https://github.com/unlcms/UNL-CMS/issues/934
