### ISSUE TITLE
Revisit Login button SVG (5.0)

### ISSUE THREAD

**Issue by tlemburg** [unl/wdntemplates#1108]
I realized that every time I look at it, I have a thought in the back of my head saying "That's super ugly." Not sure if the SVG just doesn't look too good at the size it's at, it doesn't compare well with the other SVG's like it, or something else, but it looks a little placeholder-y or janky. Something sharper would look better, and perhaps the menu icon and search icons could match it better.

**Comment by skoolbus39** [comment]
I feel your pain, but I wouldn't worry about it too much at this point. Much of what's in the header is subject to change based on usability tests and updates to the brand direction. My initial layout was not much more than attempt to catalog those things that might need to be in the header. The login button will likely need an SVG icon of some sort, but maybe not _that_ specific one and probably not _that_ layout. It's good to make note of things like this, though. If something is super ugly, continue to say so. I appreciate your attention to icon detail. It reminds me of [this A List Apart article](http://alistapart.com/article/the-king-vs-pawn-game-of-ui-design) (which reminded me of some of my own approaches to UI design). For example, notice the arrow icons in the calendar widget are sized to match the month text…

<img width="334" alt="screen shot 2018-02-13 at 5 17 59 pm" src="https://user-images.githubusercontent.com/5385125/36179460-ff0c228c-10e1-11e8-8d5d-26f5c0ac86b6.png">
…and the button borders match the stroke width of the button text:

<img width="219" alt="screen shot 2018-02-13 at 5 18 11 pm" src="https://user-images.githubusercontent.com/5385125/36179477-0f181f6e-10e2-11e8-9f10-ed3dbe19f2dd.png">
