### ISSUE TITLE
Configure hoverintent plugin; implement hover on mega menu

### ISSUE THREAD

**Issue by skoolbus39** [unl/wdntemplates#1153]
- [hoverintent plugin](https://www.npmjs.com/package/hoverintent) has been [installed](https://github.com/unl/wdntemplates/pull/1147/commits/49804deadb549c02151ec49c8e12035a2c882881) but needs to be configured
- Implement hover on mega menu toggle and primary navigation labels

**Comment by skoolbus39** [comment]
Due Tuesday

**Comment by ericras** [comment]
I still want to go on the record that I oppose the hover
