### ISSUE TITLE
Size radios, checkboxes similar to text inputs

### ISSUE THREAD

**Issue by skoolbus39** [unl/wdntemplates#1155]
[We've updated the radios and checkboxes on GOV.UK](https://designnotes.blog.gov.uk/2016/11/30/weve-updated-the-radios-and-checkboxes-on-gov-uk/)

**Comment by Shaderpixel** [comment]
Additional resource: [Accessible Styled Form Controls](Accessible Styled Form Controls)

**Comment by skoolbus39** [comment]
Fixed by #1290
