### ISSUE TITLE
Display of custom bullets

### ISSUE THREAD

**Issue by beckyaiken** [unl/wdntemplates#1157]
There are some inconsistencies between how the new custom bullets display, both across browsers but also within the same list. They appear squished or stretched in certain cases.

Chrome | Firefox
------------ | -------------
![image](https://user-images.githubusercontent.com/37584508/47042569-349c1300-d151-11e8-999f-32e2099c13f8.png) | ![image](https://user-images.githubusercontent.com/37584508/47042637-6b722900-d151-11e8-83c3-93ca415a6dae.png)

**Comment by skoolbus39** [comment]
Fixed by #1186
