### ISSUE TITLE
Areas with extra or unneeded bullets 

### ISSUE THREAD

**Issue by beckyaiken** [unl/wdntemplates#1158]
The following areas either within Drupal or the 4.1 framework need styles (or classnames) added to remove the custom bullets:

**Menu block and book navigation** (also need overrides to remove default li spacing)
![image](https://user-images.githubusercontent.com/37584508/47043493-644c1a80-d153-11e8-8e34-734c55997bd8.png)

**Book table of contents**
![image](https://user-images.githubusercontent.com/37584508/47043578-93628c00-d153-11e8-863d-8465c605175e.png)

**Tabs**
![image](https://user-images.githubusercontent.com/37584508/47043747-0a982000-d154-11e8-95c6-1812c6540973.png)

**Carousel**
![image](https://user-images.githubusercontent.com/37584508/47043773-1c79c300-d154-11e8-9d46-8026c50fe888.png)

**Drupal edit buttons**
![image](https://user-images.githubusercontent.com/37584508/47043795-2ef3fc80-d154-11e8-992a-f3297df2de40.png)

**Comment by skoolbus39** [comment]
I knew there were going to be some areas in the framework and CMS that would need to hide these custom bullets but now I'm reconsidering including them for launch. They're nice to have, not need to have. We can revisit them next year and, after more thorough testing, consider including them at a later date. Thank you for pointing these out, @beckyaiken.

**Comment by skoolbus39** [comment]
Fixed by #1186
