### ISSUE TITLE
Footer bullet alignment

### ISSUE THREAD

**Issue by beckyaiken** [unl/wdntemplates#1159]
Ideally, site-specific lists and headings will inherit styles by default so users don't need to add classnames in order for them to match the other footer content.

However, I did notice that the bullets that are in the footer now are off in their alignment when the li wraps to a 2nd line. I think it's related to the footer links being set to display inline-block.

![image](https://user-images.githubusercontent.com/37584508/47049433-e6900b00-d162-11e8-9397-44fff7a9f622.png)

**Comment by skoolbus39** [comment]
Fixed by #1186
