### ISSUE TITLE
Configure/generate "mustard" CSS/JS for older browsers

### ISSUE THREAD

**Issue by skoolbus39** [unl/wdntemplates#1161]
First: [some background](https://css-tricks.com/server-side-mustard-cut/) on "cutting the mustard."

- [Can Preload Cut the Mustard?](https://www.filamentgroup.com/lab/preload-ctm.html) which ultimately recommends still using [loadJS](https://github.com/filamentgroup/loadJS/)
- [CSS Only Mustard Cut](https://github.com/Fall-Back/CSS-Mustard-Cut)
- Stripe details how they load a fallback stylesheet at the end of this [blog post](https://stripe.com/blog/connect-front-end-experience).

**Comment by jsturek** [comment]
Solution merged into 5.0
