### ISSUE TITLE
Remove jQuery hoverIntent plugin

### ISSUE THREAD

**Issue by skoolbus39** [unl/wdntemplates#1178]
The [vanilla JavaScript version](https://github.com/unl/wdntemplates/pull/1175) should be used instead.

**Comment by skoolbus39** [comment]
The [month widget](https://github.com/unl/wdntemplates/blob/develop/wdn/templates_5.0/js-src/monthwidget.js) still uses jQuery hoverIntent.

**Comment by jsturek** [comment]
Addressed with: https://github.com/unl/wdntemplates/pull/1322
