### ISSUE TITLE
search broken in Edge

### ISSUE THREAD

**Issue by cmdprompt** [unl/wdntemplates#1202]
Edge: 42.17134.1.0
![image](https://user-images.githubusercontent.com/735416/48446238-57284880-e75e-11e8-9f2a-bb269174178e.png)

**Comment by skoolbus39** [comment]
Search has been updated recently and no longer appears to be broken in Edge. If issues persist, please reopen.

**Comment by skoolbus39** [comment]
Search has been updated recently and no longer appears to be broken in Edge. If issues persist, please reopen.

<img width="527" alt="Screen Shot 2023-08-16 at 4 01 15 PM" src="https://github.com/unl/wdntemplates/assets/5385125/e5f9d63b-831a-460f-9481-8bfb41588bc0">
