### ISSUE TITLE
Explain object-fit polyfill in documentation

### ISSUE THREAD

**Issue by beckyaiken** [unl/wdntemplates#1220]
I was looking at some hero code and found this in the CSS:

![image](https://user-images.githubusercontent.com/37584508/49234719-30a11900-f3be-11e8-8a5e-06cf1825e67d.png)

`font-family: "object-fit:cover";`

I don't think it's hurting anything, but figured I'd point it out just in case.

**Comment by skoolbus39** [comment]
Thank you!

**Comment by skoolbus39** [comment]
Documentation has (finally) been added: https://wdn.unl.edu/50-css-classes#dcf-utilities-object-fit
