### ISSUE TITLE
404 Page in 5.0

### ISSUE THREAD

**Issue by beckyaiken** [unl/wdntemplates#1227]
Layout/footer display issues with default 404 page

![image](https://user-images.githubusercontent.com/37584508/49663693-134ef900-fa15-11e8-800a-c656f26bfe95.png)
![image](https://user-images.githubusercontent.com/37584508/49663758-41ccd400-fa15-11e8-95b6-e8005e128084.png)

https://wdn.unl.edu/asdf

**Comment by ericras** [comment]
404 page has been updated in the CMS for 5.0: https://wdn.unl.edu/asdf

(Note that you won't see it on a site when merely previewing 5.0, but it will be there when 5.0 is set as the default theme, like on the wdn site currently.)
