### ISSUE TITLE
Updated events bands break out of containers

### ISSUE THREAD

**Issue by beckyaiken** [unl/wdntemplates#1235]
The updated styles for events band cause them to break out of their containers. Although it is an events "band" widget, it's not uncommon for sites to have them nested inside a grid or on a page with a sidebar rather than always going the full width of the page.

![image](https://user-images.githubusercontent.com/37584508/49883272-ef662b80-fdf7-11e8-8404-24f29f38aa2e.png)
![image](https://user-images.githubusercontent.com/37584508/49883409-43711000-fdf8-11e8-88b3-81ba6f6248c1.png)

**Comment by ericras** [comment]
The solution for when its in a sidebar or small container is to switch to "events" rather than "events-band".

For the case when its in a large container, like a 75% column, I think that's something to further work on (?)
