### ISSUE TITLE
Scroll Watch plugin not working in 5.0

### ISSUE THREAD

**Issue by anne-h** [unl/wdntemplates#1243]
The Scroll Watch plugin is not working in 5.0. 
https://wdn.unl.edu/documentation/unledu-web-framework/plugins-and-widgets/scroll-watch

I moved WDN.initializePlugin('band_imagery'); to the Appearance>Settings 5.0 CSS JavaScript tab and that didn't fix it. 

example page
https://ianr.unl.edu/growing/nebraskas-irrigation-history-its-complicated

**Comment by ncolgrove** [comment]
It appears the scroll watch uses `$(window).load(imageryUpdate)...` to bind to the JavaScript "load" event for the window. This shortcut was [deprecated in 1.8 and removed in 3.0](http://api.jquery.com/load-event/).  Changing to `$(window).on( "load", imageryUpdate )...` should correct.
