### ISSUE TITLE
Troubleshoot Travis CI errors for CSS Environment Variables

### ISSUE THREAD

**Issue by skoolbus39** [unl/wdntemplates#1248]
Pull requests are failing in Travis CI because of [CSS Environment Variables](https://css-tricks.com/css-environment-variables/). These are used to add padding to the mobile toolbar (Menu, Search, Log In, Chat) located at the bottom of the viewport. The padding creates a safe area, preventing the toolbar from colliding with an [iPhone](https://css-tricks.com/the-notch-and-css/)'s home indicator.

**Comment by ericras** [comment]
Maybe this?  prefixed rules --

--safe-area-inset-bottom: env(safe-area-inset-bottom);

https://medium.com/@draganeror/iphone-x-layout-features-with-css-environment-variables-d57423433dec

**Comment by ericras** [comment]
At the very least, take it out of critical css so that it doesn't trigger the validator

**Comment by ericras** [comment]
.unl .dcf-nav-toggle-group {
    --safe-area-inset-bottom: env(safe-area-inset-bottom);
    padding-bottom: var(--safe-area-inset-bottom);
}
