### ISSUE TITLE
WebAudit error caused by aria-haspopup

### ISSUE THREAD

**Issue by beckyaiken** [unl/wdntemplates#1256]
Following the switch to 5.0, site scores are dropping as a result of the error:

>  Bad value “dialog” for attribute “aria-haspopup” on element “button”.

It seems to be on 2 search buttons on every page. 

More info on the error: https://webaudit.unl.edu/sites/774/pages/6656037/marks/132117130/

**Comment by ericras** [comment]
validator.unl.edu is updated
