### ISSUE TITLE
UNL Events Calendar

### ISSUE THREAD

**Issue by anne-h** [unl/wdntemplates#1263]
I used to be able to click on my event calendar, then search for "seminar" by clicking the tiny search icon on the dark grey Event Managers bar,  it would display all the events in the system with "seminar" in the title and, even though I wasn't subscribed to the calendar, I could change the Action dropdown to "Move to Upcoming" and it would add the event to my calendar. When I select "Move to Upcoming" now, nothing happens. Plus there are now two extra text boxes displaying under the action dropdown. One is blank and one has a number in it (see attached screenshot). 
![screen shot 2019-01-09 at 1 30 08 pm](https://user-images.githubusercontent.com/28907070/50924415-23dc0000-1415-11e9-92b6-a76a3a9b08c7.png)

https://events.unl.edu/manager/seminars/search/?search_term=seminar

**Comment by jsturek** [comment]
@anne-h, I've made some updates.  Please verify the update resolves this issue.

**Comment by anne-h** [comment]
@jsturek The extra text fields are gone now. I have to subscribe to a calendar for the dropdown options to work, like moving an event to "upcoming". Before I could add them to upcoming without being subscribed but maybe that was a bug and not by design.  I'll just subscribe to them for now on. Thanks.
