### ISSUE TITLE
Search result headers don't appear on some Windows/Chrome computers

### ISSUE THREAD

**Issue by ericras** [unl/wdntemplates#1295]
![image](https://user-images.githubusercontent.com/446357/55578915-a30f6600-56dc-11e9-97e9-e05b7a721979.png)

**Comment by ericras** [comment]
Someone showed me a similar issue on her laptop at a meeting last week.  When I used Chrome’s “private” mode on her laptop it was ok, so I chalked it up to a setting or browser extension on her computer (like an Ad Blocker or something).

**Comment by ericras** [comment]
On that machine, it looked like the headings weren't even in the markup at all.  (They were not hidden)

**Comment by mwolff-unl** [comment]
Firefox will have the issue sometimes too.

![image](https://user-images.githubusercontent.com/8961061/55838114-f3c1fd00-5ae8-11e9-9529-cc7b3b7fb58d.png)

**Comment by ericras** [comment]
@mwolff-unl you may be right, it may be a cookie thing and not an extension thing.  If you're able to further isolate it, it would be appreciated.

**Comment by ericras** [comment]
I was able to make it happen but nothing stood out about the cookies compared to successful loads
<img width="1314" alt="Screen Shot 2019-04-09 at 5 20 53 PM" src="https://user-images.githubusercontent.com/446357/55839277-ee66b180-5aec-11e9-9752-ed6f1f54cc27.png">
<img width="1345" alt="Screen Shot 2019-04-09 at 5 21 02 PM" src="https://user-images.githubusercontent.com/446357/55839278-ee66b180-5aec-11e9-9f5d-c23a1a3cd676.png">

**Comment by ericras** [comment]
I've figured out a couple things.

Good and bad loads have different markup.
- Good load: table.gsc-table-result
- Bad load: div.gsc-table-result

The title that we are displaying is not present at all in the bad load.  There is a second title that we are hiding that is present in both versions.

**Comment by ericras** [comment]
in addition .gs-web-image-box change to margin-right: 1em; and change .unl .gs-snippet to margin-top 0

**Comment by ericras** [comment]
bad on the left, good on the right

<img width="1267" alt="Screen Shot 2019-04-09 at 6 43 40 PM" src="https://user-images.githubusercontent.com/446357/55842030-6d60e780-5af7-11e9-8a92-2cf46e1a5e6b.png">

**Comment by ericras** [comment]
Fixed in the UNL_Search project: https://git.unl.edu/iim/UNL_Search/commit/ef708c561bb6ec8e257ff10c1bff9c35cca639f2
