### ISSUE TITLE
Webforms: Attribute “step” not allowed on element “input”

### ISSUE THREAD

**Issue by kmcguffey2** [unl/wdntemplates#1317]
Number fields in webforms are showing the error 'Attribute “step” not allowed on element “input” at this point' in Web Audit.
I think the issue is that the input element has a type attribute of "text" instead of "number".

**Comment by skoolbus39** [comment]
I think this is more of a CMS issue, Keith. I'm closing the issue here and moving it to the [UNLcms project](https://github.com/unlcms/UNL-CMS/issues/947).
