### ISSUE TITLE
New pages displaying on Main Menu though user didn't check "display in menu"

### ISSUE THREAD

**Issue by anne-h** [unl/wdntemplates#1319]
IANR News and CASNR site users reported that they created new article pages this week and the pages displayed on the site's main menu. They didn't check the "display in menu" option on the edit article page. It happed twice on IANR News and once on CASNR. When I went to fix it, the "display in menu" was unchecked on the edit article page. However, it was checked on the "Navigation Links" screen Home>Administration>Structure>Menu. I tried unchecking it on the menu page and clicked "Save configuration" but the page kept redrawing with it still checked. The only way to get it off the menu was to click "edit" next to the article on the menu page and uncheck "Enabled" menu links, then save.

**Comment by skoolbus39** [comment]
@anne-h, This is more of a UNLcms issue than a framework issue. I'm closing it here and have opened your issue in the UNLcms project: https://github.com/unlcms/UNL-CMS/issues/950
