### ISSUE TITLE
Search modal stuck open on page load with 5.0.10 includes but newer CSS

### ISSUE THREAD

**Issue by ericras** [unl/wdntemplates#1349]
If a site is using the main template (https://github.com/unl/wdntemplates/blob/develop/Templates/fixed.dwt) then they have local html includes that may not sync until overnight but the html document fetches core.css from unlcms.unl.edu.  So it may be that the version of the html includes doesn't match the css/js.  (In the future this needs to be eliminated, but that will be for 5.1 or 6.0: #1348)

This was eliminated in 5.0.11 that is needed for a site that still has 5.0.10 includes:
https://github.com/d-c-n/dcf/commit/5902364a459a62cc2d46457decfc9ce96b7c470d#diff-13ba1e99069ebd6d875c7b3ceafc2c19

Possible solutions (or ways to think about this):
1) DCF needs to be better versioned (or versioned period) and not remove things until a major version change - (can be moved to a deprecated file in minor releases).  A major version change would then be a really big red flag for downstream themes to test an update to DCF.
2) DCF needs to be better versioned and removing things is fine - but it needs a CHANGELOG file that helps document changes to be aware of upon updating.
3) Even with (2), UNL would still have a problem. This isn't DCF's fault and is UNL's fault for doing a local/cloud template (#1348). UNL's theme adds https://github.com/d-c-n/dcf/commit/5902364a459a62cc2d46457decfc9ce96b7c470d#diff-13ba1e99069ebd6d875c7b3ceafc2c19 in some sort of css "bridge" file that gets included in core then removed with the next release.

Search modal classes:

```
5.0.10
page load
dcf-modal-overlay dcf-mobile-toolbar-modal dcf-bg-overlay-light dcf-p-0
open
dcf-modal-overlay dcf-mobile-toolbar-modal dcf-bg-overlay-light dcf-p-0 dcf-modal-open

5.0.13 
page load
dcf-modal-overlay dcf-bg-overlay-light dcf-p-0 dcf-invisible unl-search-modal
open
dcf-modal-overlay dcf-bg-overlay-light dcf-p-0 unl-search-modal
```

```
css in 5.0.10
.dcf-modal-overlay[aria-hidden="true"] {
    opacity: 0;
    pointer-events: none;
    -webkit-transition: opacity .4s ease-out,visibility 0ms .4s;
    transition: opacity .4s ease-out,visibility 0ms .4s;
    visibility: hidden;
}

css in 5.0.13  
.unl-search-modal[aria-hidden="true"] {
    opacity: 0;
    pointer-events: none;
    -webkit-transition: opacity .4s ease-out;
    transition: opacity .4s ease-out;
}
```

**Comment by ericras** [comment]
This really seems to be a mismatched includes & css (local & cloud/cdn combined) problem.

I don't have an explanation at this time for why a local implementation like @cmdprompt has would have had the problem.

**Comment by skoolbus39** [comment]
I agree we need to version DCF.

The reason for the changes to the modal was to [fix the broken modals for those using `prefers-reduced-motion`](https://github.com/unl/wdntemplates/pull/1332). In retrospect, I probably should have used the existing DCF class instead of changing it to a theme class. I'll work on getting the styles present for both to account for mismatched include files and CSS.

**Comment by ericras** [comment]
Do we need a transition css file in which 
.dcf-modal-overlay[aria-hidden="true"] {
    opacity: 0;
    pointer-events: none;
    -webkit-transition: opacity .4s ease-out,visibility 0ms .4s;
    transition: opacity .4s ease-out,visibility 0ms .4s;
    visibility: hidden;
}

can be included then removed later (next release)?

**Comment by ericras** [comment]
#1359 1359
