### ISSUE TITLE
.unl-bg-lightest-gray is broken 

### ISSUE THREAD

**Issue by ncolgrove** [unl/wdntemplates#1450]
Currently the class .unl-bg-lightest-gray is broken in 5.2. I think the css definition in [background-colors.scss](https://github.com/unl/wdntemplates/blob/c2dbb383611dccf9b2e48ad28a612aa6da9548bc/wdn/templates_5.2/scss/mixins/_mixins.background-colors.scss) has the incorrect color variable name. It appears to be missing the "T" in lightest.  

![wdntemplates 2020-08-18 14-34-03](https://user-images.githubusercontent.com/5377727/90557670-7d172400-e160-11ea-8c30-74fe6965b3fe.png)

![image](https://user-images.githubusercontent.com/5377727/90557785-acc62c00-e160-11ea-9101-8c4916925ed7.png)

**Comment by skoolbus39** [comment]
Thanks for filing this issue, @ncolgrove
