### ISSUE TITLE
Default images do not allow 'alt' attribute

### ISSUE THREAD

**Issue by kmcguffey2** [unl/wdntemplates#1464]
The default image option for image fields in content types do not have an alternate text field. This causes accessibility issues. 

Example: IANR News Article content type - https://ianrnews.unl.edu/admin/structure/types/manage/article/fields/field_image

**Comment by skoolbus39** [comment]
This is a CMS issue so I'm closing it here and moving it to the CMS repo: https://github.com/unlcms/UNL-CMS/issues/959
