### ISSUE TITLE
Webform calendar popup accessibility

### ISSUE THREAD

**Issue by kmcguffey2** [unl/wdntemplates#1479]
The image for the calendar popup on Webforms is being flagged by Web Audit as an accessibility error.
“ARIA hidden element must not contain focusable elements”
Example: https://webaudit.unl.edu/sites/835/pages/10202664/

**Comment by skoolbus39** [comment]
This is a UNLcms issue. I've moved it here: https://github.com/unlcms/UNL-CMS/issues/961
