### ISSUE TITLE
UNL Announce - Manage News Search Pagation Clears Search Textbox

### ISSUE THREAD

**Issue by snrwebmaster** [unl/wdntemplates#1646]
When searching for an old existing news item in "Manage News"   in the 'Archived' section, if  your item is not on the first page and you click on the pagination buttons on the bottom, other than '1',  the results revert back to the initial results WITHOUT the text search variable and back to the original list.  The only way to find a specific item is to know most of the title and search for that, hoping that the result is on the first page.    Can this be fixed so that when clicking on a pagination button the results are further down the list of results?

**Comment by skoolbus39** [comment]
Moved to UNL Announce: https://github.com/unl/UNL_ENews/issues/103
