### ISSUE TITLE
Improper display of user's name (cultural issue)

### ISSUE THREAD

**Issue by ericras** [unl/wdntemplates#751]
The IDM area is now displaying the logged in user's name in the format "Eric R."

I believe with most Asian names, such as Yao Ming, you would only ever display them as "Yao" or "Yao Ming" but never "Yao M." or "Ming".

So I suppose the suggested fix is to only show first name.

Related to change e4784d239b6956a9b5850b6e622b1f43740f5e24

**Comment by skoolbus39** [comment]
I like the suggestion of using only a person's first name.
