### ISSUE TITLE
Remove the comments link in the footer

### ISSUE THREAD

**Issue by mfairchild365** [unl/wdntemplates#826]
The comments link points to an old system.  The functionality for comments is now handled by UNLchat.

**Comment by kabel** [comment]
This was completed at 4ab449cc8014c52be2932b1c7d4347344bbdc1e8 but because it technically exists in a area that is fully editable by the developer ("sharedcode"), communication will be require to fully purge it from existing and new UNLcms sites.

**Comment by kabel** [comment]
This has now been documented on the WDN site in the announcement section.
