### ISSUE TITLE
go.unl.edu

### ISSUE THREAD

**Issue by snrwebmaster** [unl/wdntemplates#827]
There are a number of issues I love to see fixed, modified or changed on the go.un.edu application.

Your URLS
The design of the results are not easily scanable.  You need to review each band.  The old table design where information is in columns is much more usable.  

The order of them is not helpful.  Alphabetical is my preference or at least the most first.  Right now I have been told that it is by date submitted but it does not seem to be working that way.

If your go to Your URLS do anything such as delete or want to add new one you have to use the browser back button.  There are no breadcrumbs to help with navigation

Log In
When you log in  The log in area does not acknowledge that you have logged in

**Comment by kabel** [comment]
These notes have been saved to our internal project system and moved to the GoURL repo at https://github.com/unl/GoURL/issues/5
