### ISSUE TITLE
skipnav doesn't work in some browsers

### ISSUE THREAD

**Issue by mfairchild365** [unl/wdntemplates#829]
I've been experimenting with VoiceOver lately, and have noticed that in Chome and Firefox when you click the `skip navigation` link, it visually positions you at the `#maincontent` area, but when you press tab or try to interact with the page, it brings you to the next element after the `skip navigation` link, which seems frustrating and unexpected.

I've done some expirmenting and a little research and it appears that the solution is to add a `tabindex="-1"` to the maincontent area.

https://carmenwiki.osu.edu/display/10292/HTML5+Accessibility+Code+Examples
http://www.bignerdranch.com/blog/web-accessibility-skip-navigation-links/

I think this would require editing the Template HTML, which we can't do until the next major release.  One solution might be to do it with JavaScript.

**Comment by kabel** [comment]
JavaScript seems like the best solution, as we've seem in the Sheldon framework.

**Comment by mfairchild365** [comment]
@kabel do you think this should go in `navigation.js`, or `WDN.js`, or perhaps `main.js`?

**Comment by kabel** [comment]
I would suggest creating a new module to handle it and then require it in main.

**Comment by mfairchild365** [comment]
Any suggestions on what to call the new module?  Do we want it to be generic (something like `documentmodifications.js`) or specific (`skipnav.js`)?

**Comment by kabel** [comment]
Specific is always better. It encourages single function/purpose modules.
