### ISSUE TITLE
Ordering transcripts typo Country/Country

### ISSUE THREAD

**Issue by alangewisch** [unl/wdntemplates#841]
The form for ordering a paper transcript asks for 'County' but should be labeled 'Country'  See 

https://myred.nebraska.edu/psc/myred/NBL/HRMS/s/WEBLIB_DSHBOARD.ISCRIPT1.FieldFormula.IScript_GETPAGE?context=HC_SSS_TSRQST_OFF_GBL&path=student.main.ac

![image](https://cloud.githubusercontent.com/assets/12816882/8063292/8f26f084-0e99-11e5-8063-ae867ae5fa0b.png)

**Comment by kabel** [comment]
Hello @alangewisch, we'll try to forward this report on to the proper team. This repository is just for the brand and "template" functionality share among most the university's web sites and services.

**Comment by kabel** [comment]
On second glance, I believe the form you are filling out actually _is_ properly labeled. The place to enter/change your _country_ is at the top of the form (above address 1). _County_ is after the postal code and also appears to be optional.
