### ISSUE TITLE
Icon font to SVG

### ISSUE THREAD

**Issue by skoolbus39** [unl/wdntemplates#853]
[Ten reasons we switched from an icon font to SVG](http://ianfeather.co.uk/ten-reasons-we-switched-from-an-icon-font-to-svg/)

I'd like to use Grunticon, or something similar, to provide PNG fallbacks for IE8.

**Comment by boris1558** [comment]
Do we need a fall back for IE8 now that 2003 server is out of MS support?

**Comment by skoolbus39** [comment]
Worth considering if we move in this direction: https://css-tricks.com/accessible-svgs/
