### ISSUE TITLE
Add IE 8 to the legacy list

### ISSUE THREAD

**Issue by kabel** [unl/wdntemplates#887]
IE 8 has fallen out of the supported browser list and the upgrade warning should be displayed for it.

Signed off by: WDN Gov Board

**Comment by boris1558** [comment]
This is starting with 4.1 templates?

**Comment by kabel** [comment]
No, the plan is to roll this out in the next framework release scheduled for Sept 8. If you think that is too soon or needs more communication with the WDN as a whole, we can hold this off for the Oct 13 release.

**Comment by boris1558** [comment]
The analytics said about 4.7% and in a steady decline?

**Comment by boris1558** [comment]
I think that announcing it at 9/8 WDN meeting for an implimtation on 10/13 would be better.
