### ISSUE TITLE
scroll bar disappears shifting from mobile to desktop

### ISSUE THREAD

**Issue by cmdprompt** [unl/wdntemplates#889]
to reproduce:

1. go to www.unl.edu (desktop size)
2. change viewport width to get mobile size
3. open the menu with the hamburger
4. change viewport back to desktop size

can no longer scroll through the content.

**Comment by kabel** [comment]
This is known, acknowledged issue.

**Comment by cmdprompt** [comment]
Whoops. My mistake.

**Comment by kabel** [comment]
Fixed in 4.1
