### ISSUE TITLE
Grunt error

### ISSUE THREAD

**Issue by ericras** [unl/wdntemplates#896]
Trying to run grunt in a freshly cloned repo I get:

    Running "anonymous_task" task
    Warning: Cannot find module './node_modules/less-plugin-clean-css/node_modules/clean-css' Use --force to continue.
    Aborted due to warnings.

At https://github.com/unl/wdntemplates/blob/develop/Gruntfile.js#L313 can

    var CleanCSS = require('./node_modules/less-plugin-clean-css/node_modules/clean-css');

be changed to:

    var CleanCSS = require('clean-css');

I assume that's cool, but don't know enough about grunt.

**Comment by kabel** [comment]
You need to run `npm i` from the clone root. That installs the necessary project dependencies.
