### ISSUE TITLE
white space under nav

### ISSUE THREAD

**Issue by cmdprompt** [unl/wdntemplates#939]
Sometimes lots of whitespace is generated via what I guess is in the navigation.js script somewhere, which pushes the content down.
![whitespace-in-templates](https://cloud.githubusercontent.com/assets/735416/12240075/51d50e20-b851-11e5-89e7-719938d3592c.PNG)

**Comment by cmdprompt** [comment]
![nav-whitespace-issue](https://cloud.githubusercontent.com/assets/735416/12240105/7a1470ce-b851-11e5-87cc-8ad031adc0db.jpg)

**Comment by cmdprompt** [comment]
![unl-example](https://cloud.githubusercontent.com/assets/735416/12241317/22b02c86-b858-11e5-86dc-0d23534e3cac.jpg)

**Comment by cmdprompt** [comment]
![nse-space](https://cloud.githubusercontent.com/assets/735416/12462760/98cb19b0-bf85-11e5-8b0a-3cc67d51680d.png)

**Comment by cmdprompt** [comment]
![admissions-space](https://cloud.githubusercontent.com/assets/735416/12462827/ecc74232-bf85-11e5-87fc-4d1b6f6be787.png)

**Comment by kabel** [comment]
I believe we have adequately addressed this race condition in recent releases.
