### ISSUE TITLE
search icon in IE doesn't show

### ISSUE THREAD

**Issue by cmdprompt** [unl/wdntemplates#941]
![ie-search](https://cloud.githubusercontent.com/assets/735416/12242352/37174b68-b85e-11e5-9c86-8fad1982f02e.jpg)

**Comment by cmdprompt** [comment]
i see this has been fixed, but i still cant see it. when is the next push scheduled for fixes going out?

**Comment by kabel** [comment]
Scheduled for the 4.1.2 release on Feb. 9.
