### ISSUE TITLE
Move Mercury Display to optional, extended font set

### ISSUE THREAD

**Issue by skoolbus39** [unl/wdntemplates#946]
With 4.1, we're no longer using Mercury Display for the site title. The only other framework asset (that I can think of) that uses Mercury Display is [quotes](http://wdn.unl.edu/wdn/templates_4.1/examples/#quote.html). By restyling the quotes and moving Mercury Display from the core font package to an optional, extended package, we could be saving at least 76KB.

This will require communication with the WDN Shared Governance Board and WDN.

**Comment by kabel** [comment]
Wow, I didn't even realize we had two different versions of Mercury. I'm totally for getting rid of it!
