### ISSUE TITLE
carousel: hidden content is still focusable

### ISSUE THREAD

**Issue by mfairchild365** [unl/wdntemplates#986]
Carousel: I ran into this while testing the unl.edu home page, specifically the news carousel. Each slide is still accessible via keyboard even if the slides are currently hidden. This appears to be because they are not hidden with display:none, rather a combination of z-index, opacity, etc. This isn't marked on above matrix because it should happen in every browser.

**Comment by skoolbus39** [comment]
[DCF Slideshow](https://github.com/digitalcampusframework/dcf/blob/3.0/js/dcf-slideshow.js) is the officially supported slideshow used in the framework and corrects this issue.
