### ISSUE TITLE
notices: deprecate the data-duration attribute

### ISSUE THREAD

**Issue by mfairchild365** [unl/wdntemplates#989]
The `data-duration` attribute is used to auto hide notices after a certain amount of time. This can lead to issues, especially in the case of a11y, where important information is hidden before it can be fully read or even noticed. Its like the marquee all over again.

**Comment by skoolbus39** [comment]
Notices have been updated from those used in the 4.x ("WDN") versions of the framework to instead use [DCF Notices](https://github.com/digitalcampusframework/dcf/blob/3.0/js/dcf-notice.js). These do not include support for the `data-duration` attribute.
